        const nationCodeArr = [
            {"name": "안도라", "alpha2": "AD", "alpha3": "AND", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "아랍에미리트", "alpha2": "AE", "alpha3": "ARE", "currency": "United Arab Emirates Dirham (AED)", "currency_code": "AED"},
            {"name": "아프가니스탄", "alpha2": "AF", "alpha3": "AFG", "currency": "Afghan Afghani (AFN)", "currency_code": "AFN"},
            {"name": "앤티가 바부다", "alpha2": "AG", "alpha3": "ATG", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "앵귈라", "alpha2": "AI", "alpha3": "AIA", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "알바니아", "alpha2": "AL", "alpha3": "ALB", "currency": "Albanian Lek (ALL)", "currency_code": "ALL"},
            {"name": "아르메니아", "alpha2": "AM", "alpha3": "ARM", "currency": "Armenian Dram (AMD)", "currency_code": "AMD"},
            {"name": "앙골라", "alpha2": "AO", "alpha3": "AGO", "currency": "Angolan Kwanza (AOA)", "currency_code": "AOA"},
            {"name": "남극", "alpha2": "AQ", "alpha3": "ATA", "currency": null, "currency_code": null},
            {"name": "아르헨티나", "alpha2": "AR", "alpha3": "ARG", "currency": "Argentine Peso (ARS)", "currency_code": "ARS"},
            {"name": "아메리칸사모아", "alpha2": "AS", "alpha3": "ASM", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "오스트리아", "alpha2": "AT", "alpha3": "AUT", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "오스트레일리아", "alpha2": "AU", "alpha3": "AUS", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "아루바", "alpha2": "AW", "alpha3": "ABW", "currency": "Aruban Florin (AWG)", "currency_code": "AWG"},
            {"name": "올란드 제도", "alpha2": "AX", "alpha3": "ALA", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "아제르바이잔", "alpha2": "AZ", "alpha3": "AZE", "currency": "Azerbaijani Manat (AZN)", "currency_code": "AZN"},
            {"name": "보스니아 헤르체고비나", "alpha2": "BA", "alpha3": "BIH", "currency": "Bosnia and Herzegovina Convertible Mark (BAM)", "currency_code": "BAM"},
            {"name": "바베이도스", "alpha2": "BB", "alpha3": "BRB", "currency": "Barbadian Dollar (BBD)", "currency_code": "BBD"},
            {"name": "방글라데시", "alpha2": "BD", "alpha3": "BGD", "currency": "Bangladeshi Taka (BDT)", "currency_code": "BDT"},
            {"name": "벨기에", "alpha2": "BE", "alpha3": "BEL", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "부르키나파소", "alpha2": "BF", "alpha3": "BFA", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "불가리아", "alpha2": "BG", "alpha3": "BGR", "currency": "Bulgarian Lev (BGN)", "currency_code": "BGN"},
            {"name": "바레인", "alpha2": "BH", "alpha3": "BHR", "currency": "Bahraini Dinar (BHD)", "currency_code": "BHD"},
            {"name": "부룬디", "alpha2": "BI", "alpha3": "BDI", "currency": "Burundian Franc (BIF)", "currency_code": "BIF"},
            {"name": "베냉", "alpha2": "BJ", "alpha3": "BEN", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "생바르텔레미", "alpha2": "BL", "alpha3": "BLM", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "버뮤다", "alpha2": "BM", "alpha3": "BMU", "currency": "Bermudian Dollar (BMD)", "currency_code": "BMD"},
            {"name": "브루나이", "alpha2": "BN", "alpha3": "BRN", "currency": "Brunei Dollar (BND)", "currency_code": "BND"},
            {"name": "볼리비아", "alpha2": "BO", "alpha3": "BOL", "currency": "Bolivian Boliviano (BOB)", "currency_code": "BOB"},
            {"name": "보네르섬", "alpha2": "BQ", "alpha3": "BES", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "브라질", "alpha2": "BR", "alpha3": "BRA", "currency": "Brazilian Real (BRL)", "currency_code": "BRL"},
            {"name": "바하마", "alpha2": "BS", "alpha3": "BHS", "currency": "Bahamian Dollar (BSD)", "currency_code": "BSD"},
            {"name": "부탄", "alpha2": "BT", "alpha3": "BTN", "currency": "Bhutanese Ngultrum (BTN)", "currency_code": "BTN"},
            {"name": "부베섬", "alpha2": "BV", "alpha3": "BVT", "currency": null, "currency_code": null},
            {"name": "보츠와나", "alpha2": "BW", "alpha3": "BWA", "currency": "Botswana Pula (BWP)", "currency_code": "BWP"},
            {"name": "벨라루스", "alpha2": "BY", "alpha3": "BLR", "currency": "Belarusian Ruble (BYN)", "currency_code": "BYN"},
            {"name": "벨리즈", "alpha2": "BZ", "alpha3": "BLZ", "currency": "Belize Dollar (BZD)", "currency_code": "BZD"},
            {"name": "캐나다", "alpha2": "CA", "alpha3": "CAN", "currency": "Canadian Dollar (CAD)", "currency_code": "CAD"},
            {"name": "코코스 제도", "alpha2": "CC", "alpha3": "CCK", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "콩고 민주 공화국", "alpha2": "CD", "alpha3": "COD", "currency": "Congolese Franc (CDF)", "currency_code": "CDF"},
            {"name": "중앙아프리카 공화국", "alpha2": "CF", "alpha3": "CAF", "currency": "Central African CFA Franc (XAF)", "currency_code": "XAF"},
            {"name": "콩고 공화국", "alpha2": "CG", "alpha3": "COG", "currency": "CFA Franc BEAC (XAF)", "currency_code": "XAF"},
            {"name": "스위스", "alpha2": "CH", "alpha3": "CHE", "currency": "Swiss Franc (CHF)", "currency_code": "CHF"},
            {"name": "코트디부아르", "alpha2": "CI", "alpha3": "CIV", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "쿡 제도", "alpha2": "CK", "alpha3": "COK", "currency": "New Zealand Dollar (NZD)", "currency_code": "NZD"},
            {"name": "칠레", "alpha2": "CL", "alpha3": "CHL", "currency": "Chilean Peso (CLP)", "currency_code": "CLP"},
            {"name": "카메룬", "alpha2": "CM", "alpha3": "CMR", "currency": "Central African CFA Franc (XAF)", "currency_code": "XAF"},
            {"name": "중국", "alpha2": "CN", "alpha3": "CHN", "currency": "Chinese Yuan (CNY)", "currency_code": "CNY"},
            {"name": "콜롬비아", "alpha2": "CO", "alpha3": "COL", "currency": "Colombian Peso (COP)", "currency_code": "COP"},
            {"name": "코스타리카", "alpha2": "CR", "alpha3": "CRI", "currency": "Costa Rican Colón (CRC)", "currency_code": "CRC"},
            {"name": "쿠바", "alpha2": "CU", "alpha3": "CUB", "currency": "Cuban Peso (CUP)", "currency_code": "CUP"},
            {"name": "카보베르데", "alpha2": "CV", "alpha3": "CPV", "currency": "Cape Verdean Escudo (CVE)", "currency_code": "CVE"},
            {"name": "퀴라소", "alpha2": "CW", "alpha3": "CUW", "currency": "Netherlands Antillean Guilder (ANG)", "currency_code": "ANG"},
            {"name": "크리스마스섬", "alpha2": "CX", "alpha3": "CXR", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "키프로스", "alpha2": "CY", "alpha3": "CYP", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "체코", "alpha2": "CZ", "alpha3": "CZE", "currency": "Czech Koruna (CZK)", "currency_code": "CZK"},
            {"name": "독일", "alpha2": "DE", "alpha3": "DEU", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "지부티", "alpha2": "DJ", "alpha3": "DJI", "currency": "Djiboutian Franc (DJF)", "currency_code": "DJF"},
            {"name": "덴마크", "alpha2": "DK", "alpha3": "DNK", "currency": "Danish Krone (DKK)", "currency_code": "DKK"},
            {"name": "도미니카 연방", "alpha2": "DM", "alpha3": "DMA", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "도미니카 공화국", "alpha2": "DO", "alpha3": "DOM", "currency": "Dominican Peso (DOP)", "currency_code": "DOP"},
            {"name": "알제리", "alpha2": "DZ", "alpha3": "DZA", "currency": "Algerian Dinar (DZD)", "currency_code": "DZD"},
            {"name": "에콰도르", "alpha2": "EC", "alpha3": "ECU", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "에스토니아", "alpha2": "EE", "alpha3": "EST", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "이집트", "alpha2": "EG", "alpha3": "EGY", "currency": "Egyptian Pound (EGP)", "currency_code": "EGP"},
            {"name": "서사하라", "alpha2": "EH", "alpha3": "ESH", "currency": null, "currency_code": null},
            {"name": "에리트레아", "alpha2": "ER", "alpha3": "ERI", "currency": "Eritrean Nakfa (ERN)", "currency_code": "ERN"},
            {"name": "스페인", "alpha2": "ES", "alpha3": "ESP", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "에티오피아", "alpha2": "ET", "alpha3": "ETH", "currency": "Ethiopian Birr (ETB)", "currency_code": "ETB"},
            {"name": "핀란드", "alpha2": "FI", "alpha3": "FIN", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "피지", "alpha2": "FJ", "alpha3": "FJI", "currency": "Fijian Dollar (FJD)", "currency_code": "FJD"},
            {"name": "포클랜드 제도", "alpha2": "FK", "alpha3": "FLK", "currency": "Falkland Islands Pound (FKP)", "currency_code": "FKP"},
            {"name": "미크로네시아 연방", "alpha2": "FM", "alpha3": "FSM", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "페로 제도", "alpha2": "FO", "alpha3": "FRO", "currency": "Faroese Króna (DKK)", "currency_code": "DKK"},
            {"name": "프랑스", "alpha2": "FR", "alpha3": "FRA", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "가봉", "alpha2": "GA", "alpha3": "GAB", "currency": "Central African CFA Franc (XAF)", "currency_code": "XAF"},
            {"name": "영국", "alpha2": "GB", "alpha3": "GBR", "currency": "British Pound Sterling (GBP)", "currency_code": "GBP"},
            {"name": "그레나다", "alpha2": "GD", "alpha3": "GRD", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "조지아", "alpha2": "GE", "alpha3": "GEO", "currency": "Georgian Lari (GEL)", "currency_code": "GEL"},
            {"name": "프랑스령 기아나", "alpha2": "GF", "alpha3": "GUF", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "건지섬", "alpha2": "GG", "alpha3": "GGY", "currency": "British Pound Sterling (GBP)", "currency_code": "GBP"},
            {"name": "가나", "alpha2": "GH", "alpha3": "GHA", "currency": "Ghanaian Cedi (GHS)", "currency_code": "GHS"},
            {"name": "지브롤터", "alpha2": "GI", "alpha3": "GIB", "currency": "Gibraltar Pound (GIP)", "currency_code": "GIP"},
            {"name": "그린란드", "alpha2": "GL", "alpha3": "GRL", "currency": "Danish Krone (DKK)", "currency_code": "DKK"},
            {"name": "감비아", "alpha2": "GM", "alpha3": "GMB", "currency": "Gambian Dalasi (GMD)", "currency_code": "GMD"},
            {"name": "기니", "alpha2": "GN", "alpha3": "GIN", "currency": "Guinean Franc (GNF)", "currency_code": "GNF"},
            {"name": "과들루프", "alpha2": "GP", "alpha3": "GLP", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "적도 기니", "alpha2": "GQ", "alpha3": "GNQ", "currency": "Central African CFA Franc (XAF)", "currency_code": "XAF"},
            {"name": "그리스", "alpha2": "GR", "alpha3": "GRC", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "사우스조지아 사우스샌드위치 제도", "alpha2": "GS", "alpha3": "SGS", "currency": null, "currency_code": null},
            {"name": "과테말라", "alpha2": "GT", "alpha3": "GTM", "currency": "Guatemalan Quetzal (GTQ)", "currency_code": "GTQ"},
            {"name": "괌", "alpha2": "GU", "alpha3": "GUM", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "기니비사우", "alpha2": "GW", "alpha3": "GNB", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "가이아나", "alpha2": "GY", "alpha3": "GUY", "currency": "Guyanaese Dollar (GYD)", "currency_code": "GYD"},
            {"name": "홍콩", "alpha2": "HK", "alpha3": "HKG", "currency": "Hong Kong Dollar (HKD)", "currency_code": "HKD"},
            {"name": "허드 맥도널드 제도", "alpha2": "HM", "alpha3": "HMD", "currency": null, "currency_code": null},
            {"name": "온두라스", "alpha2": "HN", "alpha3": "HND", "currency": "Honduran Lempira (HNL)", "currency_code": "HNL"},
            {"name": "크로아티아", "alpha2": "HR", "alpha3": "HRV", "currency": "Croatian Kuna (HRK)", "currency_code": "HRK"},
            {"name": "아이티", "alpha2": "HT", "alpha3": "HTI", "currency": "Haitian Gourde (HTG)", "currency_code": "HTG"},
            {"name": "헝가리", "alpha2": "HU", "alpha3": "HUN", "currency": "Hungarian Forint (HUF)", "currency_code": "HUF"},
            {"name": "인도네시아", "alpha2": "ID", "alpha3": "IDN", "currency": "Indonesian Rupiah (IDR)", "currency_code": "IDR"},
            {"name": "아일랜드", "alpha2": "IE", "alpha3": "IRL", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "이스라엘", "alpha2": "IL", "alpha3": "ISR", "currency": "Israeli New Shekel (ILS)", "currency_code": "ILS"},
            {"name": "맨섬", "alpha2": "IM", "alpha3": "IMN", "currency": "British Pound Sterling (GBP)", "currency_code": "GBP"},
            {"name": "인도", "alpha2": "IN", "alpha3": "IND", "currency": "Indian Rupee (INR)", "currency_code": "INR"},
            {"name": "영국령 인도양 지역", "alpha2": "IO", "alpha3": "IOT", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "이라크", "alpha2": "IQ", "alpha3": "IRQ", "currency": "Iraqi Dinar (IQD)", "currency_code": "IQD"},
            {"name": "이란", "alpha2": "IR", "alpha3": "IRN", "currency": "Iranian Rial (IRR)", "currency_code": "IRR"},
            {"name": "아이슬란드", "alpha2": "IS", "alpha3": "ISL", "currency": "Icelandic Króna (ISK)", "currency_code": "ISK"},
            {"name": "이탈리아", "alpha2": "IT", "alpha3": "ITA", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "저지섬", "alpha2": "JE", "alpha3": "JEY", "currency": "British Pound Sterling (GBP)", "currency_code": "GBP"},
            {"name": "자메이카", "alpha2": "JM", "alpha3": "JAM", "currency": "Jamaican Dollar (JMD)", "currency_code": "JMD"},
            {"name": "요르단", "alpha2": "JO", "alpha3": "JOR", "currency": "Jordanian Dinar (JOD)", "currency_code": "JOD"},
            {"name": "일본", "alpha2": "JP", "alpha3": "JPN", "currency": "Japanese Yen (JPY)", "currency_code": "JPY"},
            {"name": "케냐", "alpha2": "KE", "alpha3": "KEN", "currency": "Kenyan Shilling (KES)", "currency_code": "KES"},
            {"name": "키르기스스탄", "alpha2": "KG", "alpha3": "KGZ", "currency": "Kyrgyzstani Som (KGS)", "currency_code": "KGS"},
            {"name": "캄보디아", "alpha2": "KH", "alpha3": "KHM", "currency": "Cambodian Riel (KHR)", "currency_code": "KHR"},
            {"name": "키리바시", "alpha2": "KI", "alpha3": "KIR", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "코모로", "alpha2": "KM", "alpha3": "COM", "currency": "Comorian Franc (KMF)", "currency_code": "KMF"},
            {"name": "세인트키츠 네비스", "alpha2": "KN", "alpha3": "KNA", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "조선민주주의인민공화국", "alpha2": "KP", "alpha3": "PRK", "currency": "North Korean Won (KPW)", "currency_code": "KPW"},
            {"name": "대한민국", "alpha2": "KR", "alpha3": "KOR", "currency": "South Korean Won (KRW)", "currency_code": "KRW"},
            {"name": "쿠웨이트", "alpha2": "KW", "alpha3": "KWT", "currency": "Kuwaiti Dinar (KWD)", "currency_code": "KWD"},
            {"name": "케이맨 제도", "alpha2": "KY", "alpha3": "CYM", "currency": "Cayman Islands Dollar (KYD)", "currency_code": "KYD"},
            {"name": "카자흐스탄", "alpha2": "KZ", "alpha3": "KAZ", "currency": "Kazakhstani Tenge (KZT)", "currency_code": "KZT"},
            {"name": "라오스", "alpha2": "LA", "alpha3": "LAO", "currency": "Lao Kip (LAK)", "currency_code": "LAK"},
            {"name": "레바논", "alpha2": "LB", "alpha3": "LBN", "currency": "Lebanese Pound (LBP)", "currency_code": "LBP"},
            {"name": "세인트루시아", "alpha2": "LC", "alpha3": "LCA", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "스리랑카", "alpha2": "LK", "alpha3": "LKA", "currency": "Sri Lankan Rupee (LKR)", "currency_code": "LKR"},
            {"name": "리히텐슈타인", "alpha2": "LI", "alpha3": "LIE", "currency": "Swiss Franc (CHF)", "currency_code": "CHF"},
            {"name": "라이베리아", "alpha2": "LR", "alpha3": "LBR", "currency": "Liberian Dollar (LRD)", "currency_code": "LRD"},
            {"name": "레소토", "alpha2": "LS", "alpha3": "LSO", "currency": "Lesotho Loti (LSL)", "currency_code": "LSL"},
            {"name": "리투아니아", "alpha2": "LT", "alpha3": "LTU", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "룩셈부르크", "alpha2": "LU", "alpha3": "LUX", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "라트비아", "alpha2": "LV", "alpha3": "LVA", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "리비아", "alpha2": "LY", "alpha3": "LBY", "currency": "Libyan Dinar (LYD)", "currency_code": "LYD"},
            {"name": "모로코", "alpha2": "MA", "alpha3": "MAR", "currency": "Moroccan Dirham (MAD)", "currency_code": "MAD"},
            {"name": "모나코", "alpha2": "MC", "alpha3": "MCO", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "몰도바", "alpha2": "MD", "alpha3": "MDA", "currency": "Moldovan Leu (MDL)", "currency_code": "MDL"},
            {"name": "몬테네그로", "alpha2": "ME", "alpha3": "MNE", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "생마르탱", "alpha2": "MF", "alpha3": "MAF", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "마다가스카르", "alpha2": "MG", "alpha3": "MDG", "currency": "Malagasy Ariary (MGA)", "currency_code": "MGA"},
            {"name": "마셜 제도", "alpha2": "MH", "alpha3": "MHL", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "북마케도니아", "alpha2": "MK", "alpha3": "MKD", "currency": "Macedonian Denar (MKD)", "currency_code": "MKD"},
            {"name": "말리", "alpha2": "ML", "alpha3": "MLI", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "미얀마", "alpha2": "MM", "alpha3": "MMR", "currency": "Myanmar Kyat (MMK)", "currency_code": "MMK"},
            {"name": "몽골", "alpha2": "MN", "alpha3": "MNG", "currency": "Mongolian Tugrik (MNT)", "currency_code": "MNT"},
            {"name": "마카오", "alpha2": "MO", "alpha3": "MAC", "currency": "Macanese Pataca (MOP)", "currency_code": "MOP"},
            {"name": "북마리아나 제도", "alpha2": "MP", "alpha3": "MNP", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "마르티니크", "alpha2": "MQ", "alpha3": "MTQ", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "모리타니", "alpha2": "MR", "alpha3": "MRT", "currency": "Mauritanian Ouguiya (MRU)", "currency_code": "MRU"},
            {"name": "몬트세랫", "alpha2": "MS", "alpha3": "MSR", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "몰타", "alpha2": "MT", "alpha3": "MLT", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "모리셔스", "alpha2": "MU", "alpha3": "MUS", "currency": "Mauritian Rupee (MUR)", "currency_code": "MUR"},
            {"name": "몰디브", "alpha2": "MV", "alpha3": "MDV", "currency": "Maldivian Rufiyaa (MVR)", "currency_code": "MVR"},
            {"name": "말라위", "alpha2": "MW", "alpha3": "MWI", "currency": "Malawian Kwacha (MWK)", "currency_code": "MWK"},
            {"name": "멕시코", "alpha2": "MX", "alpha3": "MEX", "currency": "Mexican Peso (MXN)", "currency_code": "MXN"},
            {"name": "말레이시아", "alpha2": "MY", "alpha3": "MYS", "currency": "Malaysian Ringgit (MYR)", "currency_code": "MYR"},
            {"name": "모잠비크", "alpha2": "MZ", "alpha3": "MOZ", "currency": "Mozambican Metical (MZN)", "currency_code": "MZN"},
            {"name": "나미비아", "alpha2": "NA", "alpha3": "NAM", "currency": "Namibian Dollar (NAD)", "currency_code": "NAD"},
            {"name": "누벨칼레도니", "alpha2": "NC", "alpha3": "NCL", "currency": "CFP Franc (XPF)", "currency_code": "XPF"},
            {"name": "니제르", "alpha2": "NE", "alpha3": "NER", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "노퍽섬", "alpha2": "NF", "alpha3": "NFK", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "나이지리아", "alpha2": "NG", "alpha3": "NGA", "currency": "Nigerian Naira (NGN)", "currency_code": "NGN"},
            {"name": "니카라과", "alpha2": "NI", "alpha3": "NIC", "currency": "Nicaraguan Córdoba (NIO)", "currency_code": "NIO"},
            {"name": "네덜란드", "alpha2": "NL", "alpha3": "NLD", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "노르웨이", "alpha2": "NO", "alpha3": "NOR", "currency": "Norwegian Krone (NOK)", "currency_code": "NOK"},
            {"name": "네팔", "alpha2": "NP", "alpha3": "NPL", "currency": "Nepalese Rupee (NPR)", "currency_code": "NPR"},
            {"name": "나우루", "alpha2": "NR", "alpha3": "NRU", "currency": "Australian Dollar (AUD)", "currency_code": "AUD"},
            {"name": "니우에", "alpha2": "NU", "alpha3": "NIU", "currency": "New Zealand Dollar (NZD)", "currency_code": "NZD"},
            {"name": "뉴질랜드", "alpha2": "NZ", "alpha3": "NZL", "currency": "New Zealand Dollar (NZD)", "currency_code": "NZD"},
            {"name": "오만", "alpha2": "OM", "alpha3": "OMN", "currency": "Omani Rial (OMR)", "currency_code": "OMR"},
            {"name": "파나마", "alpha2": "PA", "alpha3": "PAN", "currency": "Panamanian Balboa (PAB)", "currency_code": "PAB"},
            {"name": "페루", "alpha2": "PE", "alpha3": "PER", "currency": "Peruvian Nuevo Sol (PEN)", "currency_code": "PEN"},
            {"name": "프랑스령 폴리네시아", "alpha2": "PF", "alpha3": "PYF", "currency": "CFP Franc (XPF)", "currency_code": "XPF"},
            {"name": "파푸아뉴기니", "alpha2": "PG", "alpha3": "PNG", "currency": "Papua New Guinean Kina (PGK)", "currency_code": "PGK"},
            {"name": "필리핀", "alpha2": "PH", "alpha3": "PHL", "currency": "Philippine Peso (PHP)", "currency_code": "PHP"},
            {"name": "파키스탄", "alpha2": "PK", "alpha3": "PAK", "currency": "Pakistani Rupee (PKR)", "currency_code": "PKR"},
            {"name": "폴란드", "alpha2": "PL", "alpha3": "POL", "currency": "Polish Złoty (PLN)", "currency_code": "PLN"},
            {"name": "생피에르 미클롱", "alpha2": "PM", "alpha3": "SPM", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "핏케언 제도", "alpha2": "PN", "alpha3": "PCN", "currency": "New Zealand Dollar (NZD)", "currency_code": "NZD"},
            {"name": "푸에르토리코", "alpha2": "PR", "alpha3": "PRI", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "팔레스타인", "alpha2": "PS", "alpha3": "PSE", "currency": "Israeli New Shekel (ILS)", "currency_code": "ILS"},
            {"name": "포르투갈", "alpha2": "PT", "alpha3": "PRT", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "팔라우", "alpha2": "PW", "alpha3": "PLW", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "파라과이", "alpha2": "PY", "alpha3": "PRY", "currency": "Paraguayan Guarani (PYG)", "currency_code": "PYG"},
            {"name": "카타르", "alpha2": "QA", "alpha3": "QAT", "currency": "Qatari Riyal (QAR)", "currency_code": "QAR"},
            {"name": "레위니옹", "alpha2": "RE", "alpha3": "REU", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "루마니아", "alpha2": "RO", "alpha3": "ROU", "currency": "Romanian Leu (RON)", "currency_code": "RON"},
            {"name": "세르비아", "alpha2": "RS", "alpha3": "SRB", "currency": "Serbian Dinar (RSD)", "currency_code": "RSD"},
            {"name": "러시아", "alpha2": "RU", "alpha3": "RUS", "currency": "Russian Ruble (RUB)", "currency_code": "RUB"},
            {"name": "르완다", "alpha2": "RW", "alpha3": "RWA", "currency": "Rwandan Franc (RWF)", "currency_code": "RWF"},
            {"name": "사우디아라비아", "alpha2": "SA", "alpha3": "SAU", "currency": "Saudi Riyal (SAR)", "currency_code": "SAR"},
            {"name": "솔로몬 제도", "alpha2": "SB", "alpha3": "SLB", "currency": "Solomon Islands Dollar (SBD)", "currency_code": "SBD"},
            {"name": "세이셸", "alpha2": "SC", "alpha3": "SYC", "currency": "Seychellois Rupee (SCR)", "currency_code": "SCR"},
            {"name": "수단", "alpha2": "SD", "alpha3": "SDN", "currency": "Sudanese Pound (SDG)", "currency_code": "SDG"},
            {"name": "스웨덴", "alpha2": "SE", "alpha3": "SWE", "currency": "Swedish Krona (SEK)", "currency_code": "SEK"},
            {"name": "싱가포르", "alpha2": "SG", "alpha3": "SGP", "currency": "Singapore Dollar (SGD)", "currency_code": "SGD"},
            {"name": "세인트헬레나", "alpha2": "SH", "alpha3": "SHN", "currency": "Saint Helena Pound (SHP)", "currency_code": "SHP"},
            {"name": "슬로베니아", "alpha2": "SI", "alpha3": "SVN", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "스발바르 얀마옌 제도", "alpha2": "SJ", "alpha3": "SJM", "currency": "Norwegian Krone (NOK)", "currency_code": "NOK"},
            {"name": "슬로바키아", "alpha2": "SK", "alpha3": "SVK", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "시에라리온", "alpha2": "SL", "alpha3": "SLE", "currency": "Sierra Leonean Leone (SLL)", "currency_code": "SLL"},
            {"name": "산마리노", "alpha2": "SM", "alpha3": "SMR", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "세네갈", "alpha2": "SN", "alpha3": "SEN", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "소말리아", "alpha2": "SO", "alpha3": "SOM", "currency": "Somali Shilling (SOS)", "currency_code": "SOS"},
            {"name": "수리남", "alpha2": "SR", "alpha3": "SUR", "currency": "Surinamese Dollar (SRD)", "currency_code": "SRD"},
            {"name": "남수단", "alpha2": "SS", "alpha3": "SSD", "currency": "South Sudanese Pound (SSP)", "currency_code": "SSP"},
            {"name": "상투메 프린시페", "alpha2": "ST", "alpha3": "STP", "currency": "São Tomé and Príncipe Dobra (STN)", "currency_code": "STN"},
            {"name": "엘살바도르", "alpha2": "SV", "alpha3": "SLV", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "신트마르턴", "alpha2": "SX", "alpha3": "SXM", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "시리아", "alpha2": "SY", "alpha3": "SYR", "currency": "Syrian Pound (SYP)", "currency_code": "SYP"},
            {"name": "에스와티니", "alpha2": "SZ", "alpha3": "SWZ", "currency": "Swazi Lilangeni (SZL)", "currency_code": "SZL"},
            {"name": "터크스 케이커스 제도", "alpha2": "TC", "alpha3": "TCA", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "차드", "alpha2": "TD", "alpha3": "TCD", "currency": "Central African CFA Franc (XAF)", "currency_code": "XAF"},
            {"name": "프랑스령 남방 및 남극 지역", "alpha2": "TF", "alpha3": "ATF", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "토고", "alpha2": "TG", "alpha3": "TGO", "currency": "West African CFA Franc (XOF)", "currency_code": "XOF"},
            {"name": "태국", "alpha2": "TH", "alpha3": "THA", "currency": "Thai Baht (THB)", "currency_code": "THB"},
            {"name": "타지키스탄", "alpha2": "TJ", "alpha3": "TJK", "currency": "Tajikistani Somoni (TJS)", "currency_code": "TJS"},
            {"name": "토켈라우", "alpha2": "TK", "alpha3": "TKL", "currency": "New Zealand Dollar (NZD)", "currency_code": "NZD"},
            {"name": "동티모르", "alpha2": "TL", "alpha3": "TLS", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "투르크메니스탄", "alpha2": "TM", "alpha3": "TKM", "currency": "Turkmenistan Manat (TMT)", "currency_code": "TMT"},
            {"name": "튀니지", "alpha2": "TN", "alpha3": "TUN", "currency": "Tunisian Dinar (TND)", "currency_code": "TND"},
            {"name": "통가", "alpha2": "TO", "alpha3": "TON", "currency": "Tongan Paʻanga (TOP)", "currency_code": "TOP"},
            {"name": "튀르키예", "alpha2": "TR", "alpha3": "TUR", "currency": "Turkish Lira (TRY)", "currency_code": "TRY"},
            {"name": "트리니다드 토바고", "alpha2": "TT", "alpha3": "TTO", "currency": "Trinidad and Tobago Dollar (TTD)", "currency_code": "TTD"},
            {"name": "투발루", "alpha2": "TV", "alpha3": "TUV", "currency": "Tuvaluan Dollar (TVD)", "currency_code": "TVD"},
            {"name": "중화민국", "alpha2": "TW", "alpha3": "TWN", "currency": "New Taiwan Dollar (TWD)", "currency_code": "TWD"},
            {"name": "탄자니아", "alpha2": "TZ", "alpha3": "TZA", "currency": "Tanzanian Shilling (TZS)", "currency_code": "TZS"},
            {"name": "우크라이나", "alpha2": "UA", "alpha3": "UKR", "currency": "Ukrainian Hryvnia (UAH)", "currency_code": "UAH"},
            {"name": "우간다", "alpha2": "UG", "alpha3": "UGA", "currency": "Ugandan Shilling (UGX)", "currency_code": "UGX"},
            {"name": "미국령 군소 제도", "alpha2": "UM", "alpha3": "UMI", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "미국", "alpha2": "US", "alpha3": "USA", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "우루과이", "alpha2": "UY", "alpha3": "URY", "currency": "Uruguayan Peso (UYU)", "currency_code": "UYU"},
            {"name": "우즈베키스탄", "alpha2": "UZ", "alpha3": "UZB", "currency": "Uzbekistani Som (UZS)", "currency_code": "UZS"},
            {"name": "바티칸 시국", "alpha2": "VA", "alpha3": "VAT", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "세인트빈센트 그레나딘", "alpha2": "VC", "alpha3": "VCT", "currency": "East Caribbean Dollar (XCD)", "currency_code": "XCD"},
            {"name": "베네수엘라", "alpha2": "VE", "alpha3": "VEN", "currency": "Venezuelan Bolívar (VES)", "currency_code": "VES"},
            {"name": "영국령 버진아일랜드", "alpha2": "VG", "alpha3": "VGB", "currency": "British Pound Sterling (GBP)", "currency_code": "GBP"},
            {"name": "미국령 버진아일랜드", "alpha2": "VI", "alpha3": "VIR", "currency": "United States Dollar (USD)", "currency_code": "USD"},
            {"name": "베트남", "alpha2": "VN", "alpha3": "VNM", "currency": "Vietnamese Đồng (VND)", "currency_code": "VND"},
            {"name": "바누아투", "alpha2": "VU", "alpha3": "VUT", "currency": "Vanuatu Vatu (VUV)", "currency_code": "VUV"},
            {"name": "왈리스 푸투나", "alpha2": "WF", "alpha3": "WLF", "currency": "CFP Franc (XPF)", "currency_code": "XPF"},
            {"name": "사모아", "alpha2": "WS", "alpha3": "WSM", "currency": "Samoan Tala (WST)", "currency_code": "WST"},
            {"name": "예멘", "alpha2": "YE", "alpha3": "YEM", "currency": "Yemeni Rial (YER)", "currency_code": "YER"},
            {"name": "마요트", "alpha2": "YT", "alpha3": "MYT", "currency": "Euro (EUR)", "currency_code": "EUR"},
            {"name": "남아프리카 공화국", "alpha2": "ZA", "alpha3": "ZAF", "currency": "South African Rand (ZAR)", "currency_code": "ZAR"},
            {"name": "잠비아", "alpha2": "ZM", "alpha3": "ZMB", "currency": "Zambian Kwacha (ZMW)", "currency_code": "ZMW"},
            {"name": "짐바브웨", "alpha2": "ZW", "alpha3": "ZWE", "currency": "Zimbabwean Dollar (ZWL)", "currency_code": "ZWL"}
        ]


        const givenOrder = [
            { '메이져': 'cyj_major_blues_12key' },
            { '스윙 롱': 'cyj_swing_2516_12key_long' },
            { '스윙 숏': 'cyj_swing_2516_12key_short' },
            { '보사노바': 'cyj_bossa_nova_blues_12key' },
            { '슬로우 펑키': 'jsm_slow_funky_groove_12key' },
            { '메스니': 'pjh_metheny_mehldau' },
            { '네오소울': 'dunk_neo_soul_jam_track_12key' },
            { '가스펠 잼트랙': 'gospel_style_jam_track_june' },
            { '소 뷰티풀': 'kaijeong_sobeautiful_robert_glasper_12key' },
            { 'F.T.B': 'kaijeong_f.t.b_robert_glasper_12key' },
            { '필 라이크': 'feel_like_makin_love_12key_june' },
            { 'Funk popular': 'funk_popular_june' },
            { '원코드펑크': 'kaijeong_one_chord_funk_12key' },
            { '버드블루스': 'jimindorothy_bird_blues_changes_12key' },
            { '25 리하모니': 'jimindorothy_25_reharmonization_12key' },
            { '지민[리듬체인지]': 'jimindorothy_rhythm_changes_reharmonization' },
            { '용준[리듬체인지]': 'cyj_rhythm_change_12key' },
            { '마이너블루스': 'cyj_minor_blues_12key' },
            { '빌에반스': 'bill_evans_repertoire_june' },
            { '트릭송': 'tricky_songs_june' },
            { '프레드허쉬': 'fred_hersch_compositions_june' },
            { '허비핸콕': 'essential_herbie_hancock_chick_corea_june' },
            { '웨인쇼터': 'sookinjeong_wayne_shorter' },
            { '베니그린': 'yesolan_benny_green_key' },
            { '아트블래키': 'yesolan_art_blakey_jazz_key' },
            { '필름뮤직': 'yesolan_film_music_key' },
            { '라틴재즈송북': 'soyson_latin_jazz_key' },
            { '안토니오칼로스': 'soyson_antonio_carlos_key' },
            { '싱라이크쳇': 'wippen_sing_like_chet_key' },
        ];

        const givenOrderInPlayApps = [
            { '메이져': 'Major Jazz Blues 12 key (JAMMATES)' },
            // { '스윙 롱': 'Swing ???-V-I-VI 12key (Long) (JAMMATES)' },
            // { '스윙 숏': 'Swing ???-V-I-VI 12key (Short) (JAMMATES)' },
            { '스윙 롱': 'Swing VIVI 12key (Long) (JAMMATES)' },
            { '스윙 숏': 'Swing VIVI 12key (Short) (JAMMATES)' },
            { '보사노바': 'Bossa Nova Blues 12key (JAMMATES)' },
            { '슬로우 펑키': 'Slow Funk 12 key(Straight Groove) (JAMMATES)' },
            { '메스니': 'Metheny & Mehldau (JAMMATES)' },
            { '네오소울': 'Neo Soul Jam Track 12key (JAMMATES)' },
            { '가스펠 잼트랙': 'Gospel Style Jam Track (JAMMATES)' },
            { '소 뷰티풀': 'So beautiful (Robert Glasper) 12 key (JAMMATES)' },
            { 'F.T.B': 'F.T.B (Robert Glasper) 12 key (JAMMATES)' },
            { '필 라이크': 'Feel Like Makin love 12key (JAMMATES)' },
            { 'Funk popular': 'Funk Popular (JAMMATES)' },
            { '원코드펑크': 'kaijeong_one_chord_funk_12key' }, 
            { '버드블루스': 'Bird Blues Changes 12key (JAMMATES)' },
            // { '25 리하모니': '???-??? Reharmonization 12key (JAMMATES)' },
            // { '25 리하모니': '???? Reharmonization 12key (JAMMATES)' },
            { '25 리하모니': 'Reharmonization 12key (JAMMATES)' },
            { '지민[리듬체인지]': 'Rhythm Changes Reharmonization (JAMMATES)' },
            { '용준[리듬체인지]': 'Rhythm Change 12key (JAMMATES)' },
            { '마이너블루스': 'Minor Blues 12 key (JAMMATES)' },
            { '빌에반스': 'Bill Evans Repertoire (JAMMATES)' },
            { '트릭송': 'Tricky Songs (JAMMATES)' },
            { '프레드허쉬': 'fred_hersch_compositions_june' }, 
            { '허비핸콕': 'Essential Herbie Hancock & Chick corea (JAMMATES)' },
            { '웨인쇼터': 'sookinjeong_wayne_shorter' }, 
            { '베니그린': 'yesolan_benny_green_key' },  
            { '아트블래키': 'yesolan_art_blakey_jazz_key' }, 
            { '필름뮤직': 'yesolan_film_music_key' },  
            { '라틴재즈송북': 'soyson_latin_jazz_key' },  
            { '안토니오칼로스': 'soyson_antonio_carlos_key' },  
            { '싱라이크쳇': 'wippen_sing_like_chet_key' }, 
        ];
        
        function getKoreanName(productTitle) {
            for (let item of givenOrderInPlayApps) {
                if (Object.values(item).includes(productTitle)) {
                    return Object.keys(item)[0];
                }
            }
            return '';
        }

        if (typeof continent === 'undefined') {
            var continent = {
                '아시아': {
                    'KR': '한국',
                    'CN': '중국',
                    'HK': '홍콩',
                    'JP': '일본',
                    'SG': '싱가포르',
                    'TH': '태국',
                    'MY': '말레이시아',
                    'TW': '대만',
                    'VN': '베트남',
                    'ID': '인도네시아',
                    'PH': '필리핀',
                    'IN': '인도',
                    'KZ': '카자흐스탄',
                    'MO': '마카오',
                },
                '유럽': {
                    'AT': '오스트리아',
                    'BE': '벨기에',
                    'DE': '독일',
                    'ES': '스페인',
                    'FI': '핀란드',
                    'FR': '프랑스',
                    'IT': '이탈리아',
                    'NL': '네덜란드',
                    'SI': '슬로베니아',
                    'CH': '스위스',
                    'DK': '덴마크',
                    'GB': '영국',
                    'HU': '헝가리',
                    'NO': '노르웨이',
                    'RU': '러시아',
                    'SE': '스웨덴',
                    'SK': '슬로바키아',
                    'PL': '폴란드',
                    'CZ': '체코',
                    'IS': '아이슬란드',
                    'IE': '아일랜드',
                    'GR': '그리스',
                    'PT': '포르투갈',
                    'AM': '아르메니아',
                    'AZ': '아제르바이잔',
                    'LV': '라트비아',
                    'LT': '리투아니아',
                    'RO': '루마니아',
                    'EE': '에스토니아',
                    'HR': '크로아티아',
                    'UA': '우크라이나',
                    'MD': '몰도바',
                    'RS': '세르비아',
                    'BG': '불가리아',
                    'GE': '조지아',
                    'BY': '벨라루스',
                    'LU': '룩셈부르크',
                },
                '오세아니아': {
                    'AU': '호주',
                    'NZ': '뉴질랜드'
                },
                '중동': {
                    'TR': '튀르키예',
                    'AE': '아랍에미리트',
                    'IL': '이스라엘',
                    'LB': '레바논',
                    'SA': '사우디아라비아',
                    'QA': '카타르'
                },
                '아프리카': {
                    'ZA': '남아프리카공화국',
                    'EG': '이집트',
                    'MG': '마다가스카르',
                },
                '북아메리카': {
                    'US': '미국',
                    'CA': '캐나다'
                },
                '남아메리카': {
                    'AR': '아르헨티나',
                    'BR': '브라질',
                    'CO': '콜롬비아',
                    'PY': '파라과이',
                    'MX': '멕시코',
                    'DO': '도미니카공화국',
                    'CL': '칠레',
                    'BO': '볼리비아',
                    'UY': '우루과이',
                    'VE': '베네수엘라',
                    'PE': '페루',
                    'AG': '앤티가바부다',
                    'PA': '파나마',
                }
            };
        }
        
        function getCountryName(alpha2) {
            for (let continentName in continent) {
                if (continent[continentName][alpha2]) {
                    return continent[continentName][alpha2];
                }
            }
            return '알 수 없음';
        }


        const writerPackageInPlayApps = {
            '전용준': [
                { '메이져': 'Major Jazz Blues 12 key (JAMMATES)' },
                { '스윙 롱': 'Swing VIVI 12key (Long) (JAMMATES)' },
                { '스윙 숏': 'Swing VIVI 12key (Short) (JAMMATES)' },
                { '보사노바': 'Bossa Nova Blues 12key (JAMMATES)' },
                { '용준[리듬체인지]': 'Rhythm Change 12key (JAMMATES)' },
                { '마이너블루스': 'Minor Blues 12 key (JAMMATES)' },
            ],
            '전상민': [
                { '슬로우 펑키': 'Slow Funk 12 key(Straight Groove) (JAMMATES)' },
            ],
            '박종현': [
                { '메스니': 'Metheny & Mehldau (JAMMATES)' },
            ],
            '홍성준': [
                { '네오소울': 'Neo Soul Jam Track 12key (JAMMATES)' },
                { '가스펠 잼트랙': 'Gospel Style Jam Track (JAMMATES)' },
            ],
            '정성현': [
                { '소 뷰티풀': 'So beautiful (Robert Glasper) 12 key (JAMMATES)' },
                { 'F.T.B': 'F.T.B (Robert Glasper) 12 key (JAMMATES)' },
                { '필 라이크': 'Feel Like Makin love 12key (JAMMATES)' },
                { 'Funk popular': 'Funk Popular (JAMMATES)' },
                { '원코드펑크': 'kaijeong_one_chord_funk_12key' },
            ],
            '박지민': [
                { '버드블루스': 'Bird Blues Changes 12key (JAMMATES)' },
                { '25 리하모니': 'Reharmonization 12key (JAMMATES)' },
                { '지민[리듬체인지]': 'Rhythm Changes Reharmonization (JAMMATES)' },
            ],
            '김민지': [
                { '빌에반스': 'Bill Evans Repertoire (JAMMATES)' },
                { '트릭송': 'Tricky Songs (JAMMATES)' },
                { '프레드허쉬': 'fred_hersch_compositions_june' },
            ],
            '정숙인': [
                { '허비핸콕': 'Essential Herbie Hancock & Chick corea (JAMMATES)' },
                { '웨인쇼터': 'sookinjeong_wayne_shorter' },
            ],
            '안예솔': [
                { '베니그린': 'yesolan_benny_green_key' },
                { '아트블래키': 'yesolan_art_blakey_jazz_key' },
                { '필름뮤직': 'yesolan_film_music_key' },
            ],
            '손소희': [
                { '라틴재즈송북': 'soyson_latin_jazz_key' },
                { '안토니오칼로스': 'soyson_antonio_carlos_key' },
            ],
            '이지수': [
                { '싱라이크쳇': 'wippen_sing_like_chet_key' },
            ],
        }
        

        const writerPackage = {
            '전용준': [
                { '메이져': 'cyj_major_blues_12key' },
                { '스윙 롱': 'cyj_swing_2516_12key_long' },
                { '스윙 숏': 'cyj_swing_2516_12key_short' },
                { '보사노바': 'cyj_bossa_nova_blues_12key' },
                { '용준[리듬체인지]': 'cyj_rhythm_change_12key' },
                { '마이너블루스': 'cyj_minor_blues_12key' },
            ],
            '전상민': [
                { '슬로우 펑키': 'jsm_slow_funky_groove_12key' },
            ],
            '박종현': [
                { '메스니': 'pjh_metheny_mehldau' },
            ],
            '홍성준': [
                { '네오소울': 'dunk_neo_soul_jam_track_12key' },
                { '가스펠 잼트랙': 'gospel_style_jam_track_june' },
            ],
            '정성현': [
                { '소 뷰티풀': 'kaijeong_sobeautiful_robert_glasper_12key' },
                { 'F.T.B': 'kaijeong_f.t.b_robert_glasper_12key' },
                { '필 라이크': 'feel_like_makin_love_12key_june' },
                { 'Funk popular': 'funk_popular_june' },
                { '원코드펑크': 'kaijeong_one_chord_funk_12key' },
            ],
            '박지민': [
                { '버드블루스': 'jimindorothy_bird_blues_changes_12key' },
                { '25 리하모니': 'jimindorothy_25_reharmonization_12key' },
                { '지민[리듬체인지]': 'jimindorothy_rhythm_changes_reharmonization' },
            ],
            '김민지': [
                { '빌에반스': 'bill_evans_repertoire_june' },
                { '트릭송': 'tricky_songs_june' },
                { '프레드허쉬': 'fred_hersch_compositions_june' },
            ],
            '정숙인': [
                { '허비핸콕': 'essential_herbie_hancock_chick_corea_june' },
                { '웨인쇼터': 'sookinjeong_wayne_shorter' },
            ],
            '안예솔': [
                { '베니그린': 'yesolan_benny_green_key' },
                { '아트블래키': 'yesolan_art_blakey_jazz_key' },
                { '필름뮤직': 'yesolan_film_music_key' },
            ],
            '손소희': [
                { '라틴재즈송북': 'soyson_latin_jazz_key' },
                { '안토니오칼로스': 'soyson_antonio_carlos_key' },
            ],
            '이지수': [
                { '싱라이크쳇': 'wippen_sing_like_chet_key' },
            ],
        }
        